id = "panache-language-server"
name = "Panache"
description = "Language server for Quarto and other Markdown flavors"
version = "2.36.1"
schema_version = 1
authors = ["Johan Larsson <johan@jolars.co>"]
repository = "https://github.com/jolars/panache"

[language_servers.panache-language-server]
name = "Panache Language Server"
languages = ["Markdown", "Quarto", "RMarkdown"]
